# Generated by Django 3.2.25 on 2024-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avatar',
        ),
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.ImageField(default=2, upload_to='catalog/books'),
            preserve_default=False,
        ),
    ]
